/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_mem_dummy_DummyLibJni */

#ifndef _Included_com_study_mem_dummy_DummyLibJni
#define _Included_com_study_mem_dummy_DummyLibJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_mem_dummy_DummyLibJni
 * Method:    offset_meta1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_study_mem_dummy_DummyLibJni_offset_1meta1
  (JNIEnv *, jclass);

/*
 * Class:     com_study_mem_dummy_DummyLibJni
 * Method:    offset_meta2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_study_mem_dummy_DummyLibJni_offset_1meta2
  (JNIEnv *, jclass);

/*
 * Class:     com_study_mem_dummy_DummyLibJni
 * Method:    offset_meta3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_study_mem_dummy_DummyLibJni_offset_1meta3
  (JNIEnv *, jclass);

/*
 * Class:     com_study_mem_dummy_DummyLibJni
 * Method:    offset_data
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_study_mem_dummy_DummyLibJni_offset_1data
  (JNIEnv *, jclass);

/*
 * Class:     com_study_mem_dummy_DummyLibJni
 * Method:    offset_data_len
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_study_mem_dummy_DummyLibJni_offset_1data_1len
  (JNIEnv *, jclass);

/*
 * Class:     com_study_mem_dummy_DummyLibJni
 * Method:    freeMem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_study_mem_dummy_DummyLibJni_freeMem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_study_mem_dummy_DummyLibJni
 * Method:    callDummyApi
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_study_mem_dummy_DummyLibJni_callDummyApi
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
